services:
  - type: worker
    name: telegram-open-close-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false 
